import Config

# Load .env file in development (if it exists)
if File.exists?(".env") do
  File.read!(".env")
  |> String.split("\n")
  |> Enum.each(fn line ->
    case String.split(line, "=", parts: 2) do
      [key, value] when key != "" ->
        key = String.trim(key)
        value = String.trim(value)
        # Skip comments and empty lines
        unless String.starts_with?(key, "#") do
          System.put_env(key, value)
        end
      _ -> :ok
    end
  end)
end

import_config "oban.exs"

# Configure your database
# Uses DATABASE_URL from .env if set (for Neon.tech), otherwise falls back to local postgres
config :medic, Medic.Repo,
  url: System.get_env("DATABASE_URL") || "postgres://postgres:postgres@localhost/medic_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "20"),
  ssl: if(System.get_env("DATABASE_URL"), do: [verify: :verify_none], else: false)

# Oban configuration is shared in config/oban.exs

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :medic, MedicWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "sqyjAhhWA2k/0nUSSkqdJdqiTGfCYomVQIigpUBzbLXpd4xbujXJMkzPkigW2Hly",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:medic, ~w(--sourcemap=inline --watch)]},
    ssr: {Esbuild, :install_and_run, [:ssr, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :medic, MedicWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/medic_web/router\.ex$"E,
      ~r"lib/medic_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :medic, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Gmail SMTP config for development testing (uses env vars from .env)
# Set USE_SMTP=true in .env to enable real email sending in dev
# Each sender (hi@, appointments@, support@) uses its own app password
if System.get_env("USE_SMTP") == "true" do
  config :medic, Medic.Mailer,
    adapter: Swoosh.Adapters.SMTP,
    relay: "smtp.gmail.com",
    port: 587,
    username: System.get_env("HI_USERNAME") || "hi@medic.gr",
    password: System.get_env("HI_SMTP_APP"),
    ssl: false,
    tls: :if_available,
    tls_options: [verify: :verify_none],
    auth: :always,
    retries: 2,
    no_mx_lookups: false

  config :medic, Medic.AppointmentsMailer,
    adapter: Swoosh.Adapters.SMTP,
    relay: "smtp.gmail.com",
    port: 587,
    username: "appointments@medic.gr",
    password: System.get_env("APPOINTMENTS_SMTP_APP"),
    ssl: false,
    tls: :if_available,
    tls_options: [verify: :verify_none],
    auth: :always,
    retries: 2,
    no_mx_lookups: false
end
