defmodule Medic.Repo.Migrations.CreateReviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint, null: false
      add :comment, :text
      add :status, :text, null: false, default: "published"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :doctor_id,
          references(:doctors,
            column: :id,
            name: "reviews_doctor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :patient_id,
          references(:patients,
            column: :id,
            name: "reviews_patient_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :appointment_id,
          references(:appointments,
            column: :id,
            name: "reviews_appointment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:reviews, "reviews_doctor_id_fkey")

    drop constraint(:reviews, "reviews_patient_id_fkey")

    drop constraint(:reviews, "reviews_appointment_id_fkey")

    drop table(:reviews)
  end
end
