defmodule Medic.Repo.Migrations.AddEmailTemplatesAndLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:email_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :to, :text, null: false
      add :subject, :text, null: false
      add :template_name, :text
      add :status, :text, null: false, default: "sent"
      add :error, :text
      add :triggered_by, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "email_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:email_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :subject, :text, null: false
      add :html_body, :text, null: false
      add :text_body, :text
      add :sender_name, :text, null: false, default: "Medic"
      add :sender_address, :text, null: false, default: "hi@medic.gr"
      add :description, :text
      add :variables, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:email_templates, [:name], name: "email_templates_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:email_templates, [:name],
                     name: "email_templates_unique_name_index"
                   )

    drop table(:email_templates)

    drop constraint(:email_logs, "email_logs_user_id_fkey")

    drop table(:email_logs)
  end
end
