defmodule Medic.Repo.Migrations.AddDoctorProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:doctors) do
      add :title, :text
      add :pronouns, :text
      add :registration_number, :text
      add :years_of_experience, :bigint
      add :hospital_affiliation, :text
      add :academic_title, :text
      add :telemedicine_available, :boolean, default: false
      add :board_certifications, {:array, :text}, default: []
      add :sub_specialties, {:array, :text}, default: []
      add :clinical_procedures, {:array, :text}, default: []
      add :conditions_treated, {:array, :text}, default: []
      add :languages, {:array, :text}, default: []
      add :insurance_networks, {:array, :text}, default: []
      add :accessibility_items, {:array, :text}, default: []
      add :awards, {:array, :text}, default: []
      add :publications, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:doctors) do
      remove :publications
      remove :awards
      remove :accessibility_items
      remove :insurance_networks
      remove :languages
      remove :conditions_treated
      remove :clinical_procedures
      remove :sub_specialties
      remove :board_certifications
      remove :telemedicine_available
      remove :academic_title
      remove :hospital_affiliation
      remove :years_of_experience
      remove :registration_number
      remove :pronouns
      remove :title
    end
  end
end
