defmodule Medic.Repo.Migrations.CreateExperienceSubmissions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:experience_submissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :communication_style, :bigint, null: false
      add :explanation_style, :bigint, null: false
      add :personality_tone, :bigint, null: false
      add :pace, :bigint, null: false
      add :appointment_timing, :bigint, null: false
      add :consultation_style, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :doctor_id,
          references(:doctors,
            column: :id,
            name: "experience_submissions_doctor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :patient_id,
          references(:patients,
            column: :id,
            name: "experience_submissions_patient_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :appointment_id,
          references(:appointments,
            column: :id,
            name: "experience_submissions_appointment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end


  end

  def down do

    drop constraint(:experience_submissions, "experience_submissions_doctor_id_fkey")

    drop constraint(:experience_submissions, "experience_submissions_patient_id_fkey")

    drop constraint(:experience_submissions, "experience_submissions_appointment_id_fkey")

    drop table(:experience_submissions)
  end
end
