defmodule Medic.Repo.Migrations.AddSoftDeletesToUsersPatientsDoctors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:doctors) do
      add :deleted_at, :utc_datetime_usec
    end

    alter table(:patients) do
      add :deleted_at, :utc_datetime_usec
    end

    alter table(:users) do
      add :deleted_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :deleted_at
    end

    alter table(:patients) do
      remove :deleted_at
    end

    alter table(:doctors) do
      remove :deleted_at
    end
  end
end
