defmodule Medic.Repo.Migrations.CreatePatientContext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:patient_contexts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tags, {:array, :text}, default: []
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :doctor_id,
          references(:doctors,
            column: :id,
            name: "patient_contexts_doctor_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :patient_id,
          references(:patients,
            column: :id,
            name: "patient_contexts_patient_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:patient_contexts, [:doctor_id, :patient_id],
             name: "patient_contexts_unique_context_index"
           )
  end

  def down do
    drop_if_exists unique_index(:patient_contexts, [:doctor_id, :patient_id],
                     name: "patient_contexts_unique_context_index"
                   )

    drop constraint(:patient_contexts, "patient_contexts_doctor_id_fkey")

    drop constraint(:patient_contexts, "patient_contexts_patient_id_fkey")

    drop table(:patient_contexts)
  end
end
