defmodule Medic.Repo.Migrations.AddBodyToEmailLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:email_logs) do
      add :html_body, :text
    end
  end

  def down do
    alter table(:email_logs) do
      remove :html_body
    end
  end
end
