defmodule Medic.Repo.Migrations.AddCachedScheduleToDoctors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:doctors) do
      add :cached_schedule, :map, default: %{}
    end
  end

  def down do
    alter table(:doctors) do
      remove :cached_schedule
    end
  end
end
